language: android
sudo: required
dist: trusty
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - extra-android-m2repository
script:
- "./gradlew build"
before_install:
- openssl aes-256-cbc -K $encrypted_d3341840ba57_key -iv $encrypted_d3341840ba57_iv
  -in keystore.jks.enc -out keystore.jks -d
- chmod +x gradlew
- yes | sdkmanager "platforms;android-28"
- yes | sdkmanager "build-tools;28.0.3"
branches:
  only:
  - master
licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+
before_deploy:
- cd app/build/outputs/apk/release
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ../../../../../keystore.jks
  -storepass $storepass -keypass $keypass app-release-unsigned.apk keystore
- jarsigner -verify app-release-unsigned.apk
env:
  global:
  - secure: 24AyaUS8A0VU6yEaqfW+lZKrW8an+CS0659dMQHzMc8e8WmRHRxeqWf07UZ6ZyzNrY3Z5cafr4/4XdJXPexxLMSCPiIsMZbGlNQ1g0zumoxZ3PnCwIM7HzMd0HII0u9fPglsEQ0xWXwlh/ykRJ6ueUyrejHMUZsWVinwYLa4GBfv+e7Hd7egFK4yNQK0lIWVpA8j5wEsQC3WLxpYsVSoKL/GFF9Uf2ct/pr5v10dGxLeDPc/DkLgYJcvhuivdZWl4g5yVfL6drB6wnnUxOaGNWNTVn+n/sSsMqp9nrJzodKSnuuCA9Ava4RCwrRIhRTEq3VzxoZ3DVXLvA+3EIyzxdL54dH1F6/PLyvDE0dbN6cTn/gH6e2vMdcVsyB2/CRxUJL91Crq2YGqS60VX6kZ3Z57rAsWAZzgp6EkhOQ4TqhgO9/QEpfnW52ZyACTzFUgxsu0/S8KJ5rXi2LjgENO1IW8K2Fr4Xocg/AH/uAcCiNLOkZ5opR0Hdu/KkAF52ztxhqMToTBmKC/eioSzmERqRwsAkf4IKptLscJb+aeFM4Gi08WJko0irB+X9o+VAi7l/JWj92AZU/gv20mESCbadFabU8s5PvER6Hv74yKMCV/Ku36uqlQjeVRqbIO27QUYeqbs5sw5NClh67JlrBJUT/zuZ4HEoi64ae0O72rnUg=
  - secure: qFqXbjtdioFoABEtdnhYmTt/t3t/X0gbs2f/4dCvLS4UL7ekXs/2ALIICZcLr5BqRiQLfhfdxKWvj3KahseR746bNOVbYm3jdsji4Rt5bpLALaEQhTT+xQaRWq1p1KgO725ioKYX9wg5QSot9yD6DxPtN0ssOCXOv6wnT3QFVRPRdvICOCFHbE5oBOvRDrxJYH1JUdnyRiACDPoIDlXVjpPTnz6V1dg1gNBdebI5KnC1x8fvUkoLS0/qRJkB8os3+3NATu8QQkf7FCOGqrQpPNMbQ4O5iAK3taLYEHE9F2Uj0zkZHGTHLV0+OfAF+RhZ1qCE829ETclkQUA4OLvzb9L9YmKMXdHfGyK30rXyLg8Wn0jJlAwsJQXkLmY0j3BVfOBt1FxT0bo3vp0yr9WhtIvex74uEa6cb23anJCyuH2YwZPjJ0Q+iCc7jXDNjklrLU//5yd/XC52lbGZm18/EtvB4hSlGwlEFnuBrqrp33EW4P6h529BMalOW41cU8ZgKfjs0KFVVFPsKG8UzuwkIHghH7c5FHijDNQ+7HkYvLfedyphSHljz7dgLBzRBGASEEX23TVZj6/cQyt7Nu0SsWjZpuj/VPpoCc45gf+mrojaTnZAxa5n8erx5S1+wKcZEvFw5D2CNG0AZmuBATSH8Z10VLIa3ivrChXKyYf6ASE=
deploy:
  provider: releases
  api_key:
    secure: dISoqUllwklDPbww28ZxM1tMXQa7mJ13fmetAdJ7IUuNor0alMyaX7rqR5UDVLtyB1Qyp1bY8sBU3frD5otnd7ls9k8ZZH2+lMSIqrziRI6+PvJwOrjdZqjBsdT0vWovm7fW7WhoNpcnUhJx+rk9LNLPI7LmMP1Ji6yniI1HKFx0kTMqFLBbKBTwxbn2ELMgfVzHri7VgyzTfAsWoT2zuUFdeWfObIunEBZgbR1OMTg/g2hdgfRFyRdh5YxtrT1jScO/BKad5CYN8IWkEcKF6ablFVL88ufHBtwQIyd9UeI6kE+LiNY2uAGMayUzkS7+pvEYhvQWLsoSafBKbDtuD7bC+nxm1phGm8zvxnm4R9mMq5+nrgBKB4IseSGXa/rBP++h5asKHK3z4bouIuMt3g3noz2sMiHio07RLL3I0V/zBUJwZTrP2ytAkp25AARi8WnB2iGISHMeKiuq/4Xw4TSMgcPrmTOwPTNdVI5JsGlkxgC23tmqEE0fG/OrVgE7r49sYaJ5FIsK4YD9rWrnag/GxIDqxQPxpK4+BgR+c2hH01H2G5LJtTXP9Qh7uvmPu2c47kTKVyTpJvpb51VDlx/APAHQ+EcCYbR/69GZ1Xww9zCaL2BCNq2MJlqT4uIwBv/t1+FMnikQtf0tSw5161w7nF3o+DcmlNn4INC+/LU=
  file: app-release-unsigned.apk
  skip_cleanup: true
  on:
    repo: adrianwithah/DigitalMenu
